<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Acart
 */


namespace Amasty\Acart\Model;

use Magento\Framework\UrlInterface;

class UrlManager extends \Magento\Framework\DataObject
{
    protected $_rule;
    protected $_history;
    protected $_frontUrlModel;

    const PATH_URL_REGEXP_PATTERN = '/[^a-zA-Z0-9_ %\[\]\.\(\)%&-\/]/s';

    protected $_googleAnalyticsParams
        = [
            'utm_source',
            'utm_medium',
            'utm_term',
            'utm_content',
            'utm_campaign'
        ];

    /**
     * Constructor
     *
     * By default is looking for first argument as array and assigns it as object attributes
     * This behavior may change in child classes
     *
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\Url $frontUrlModel,
        array $data = []
    ) {
        $this->_frontUrlModel = $frontUrlModel;

        parent::__construct($data); // TODO: Change the autogenerated stub
    }

    public function init(
        \Amasty\Acart\Model\Rule $rule,
        \Amasty\Acart\Model\History $history
    ) {
        $this->_rule = $rule;
        $this->_history = $history;

        return $this;
    }

    public function getRule()
    {
        return $this->_rule;
    }

    /**
     * Add params to URL query
     * add google Analytics
     *
     * @since 1.0.6 Google Analitics moved to _query (after ?)
     * @param array $params
     *
     * @return array
     */
    protected function getParams($params = [])
    {
        $params["id"] = $this->_history->getId();
        $params["key"] = $this->_history->getPublicKey();

        $params["_nosid"] = true;
        $params["_query"] = ['___store' => $this->_history->getStore()->getCode()];

        foreach ($this->_googleAnalyticsParams as $param) {
            $val = $this->_rule->getData($param);
            if (!empty($val)) {
                $params["_query"][$param] = $val;
            }
        }

        return $params;
    }

    public function get($url)
    {
        return $this->_frontUrlModel->getUrl(
            'amasty_acart/email/url',
            $this->getParams(['url' => urlencode(base64_encode($url))])
        );
    }

    public function mageUrl($url)
    {
        return $this->_frontUrlModel->getUrl(
            'amasty_acart/email/url',
            $this->getParams(['mageUrl' => urlencode(base64_encode($url))])
        );
    }

    public function unsubscribeUrl()
    {
        return $this->_frontUrlModel->getUrl('amasty_acart/email/unsubscribe', $this->getParams());
    }

    /**
     * @param $urlString
     * @return string
     */
    public function getCleanUrl($urlString)
    {
        return preg_replace(self::PATH_URL_REGEXP_PATTERN, '', $urlString);
    }
}